# Generated by Django 5.1.3 on 2025-01-01 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserMemoryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_memory', models.TextField(default='')),
                ('last_processed_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_processed', to='api.message')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
