# Generated by Django 5.1.3 on 2025-03-13 13:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_is_user_usermemorystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.CharField(choices=[('Beginning', 'BEGINNING'), ('Intermediate', 'INTERMEDIATE'), ('Advanced', 'ADVANCED')], default=api.models.Stage['BEGINNING'], max_length=20),
        ),
    ]
