# Generated by Django 5.1.3 on 2025-07-09 15:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('control', 'CONTROL'), ('intervention', 'INTERVENTION')], default=api.models.UserGroup['CONTROL'], help_text="User's assigned group (control or intervention). Should be set once and not changed.", max_length=20),
        ),
    ]
