# Generated by Django 5.1.3 on 2025-07-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(
                choices=[('control', 'CONTROL'), ('intervention', 'INTERVENTION')],
                default=api.models.UserGroup['CONTROL'],
                help_text="User's assigned group (control or intervention). Should be set once and not changed.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='UserDayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('current_day', models.IntegerField(default=1)),
                ('last_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
