# Generated by Django 5.2.5 on 2025-08-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.CharField(blank=True, help_text='FSM state when message was created', max_length=50, null=True),
        ),
    ]
