# Generated by Django 5.1.3 on 2025-08-30 08:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('control', 'CONTROL'), ('intervention', 'INTERVENTION'), ('placebo', 'PLACEBO')], default=api.models.UserGroup['CONTROL'], help_text="User's assigned group (control or intervention). Should be set once and not changed.", max_length=20),
        ),
    ]
